
import { Product } from '../types';

export const INITIAL_CATEGORIES = ['Điện tử', 'Thời trang', 'Gia dụng', 'Laptop', 'Phụ kiện', 'Sách', 'Linh kiện PC'];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Tai nghe Sony WH-1000XM5',
    price: 6990000,
    costPrice: 5500000,
    category: 'Điện tử',
    condition: 'Hàng chính hãng 100%',
    description: 'Tai nghe chống ồn hàng đầu thế giới với chất âm tuyệt hảo và thiết kế siêu nhẹ.',
    specs: "Pin: 30 giờ (NC on)\nChống ồn: Active Noise Cancellation (ANC)\nKết nối: Bluetooth 5.2\nTrọng lượng: 250g\nCổng sạc: USB-C",
    warrantyPeriod: "12 tháng",
    image: 'https://picsum.photos/seed/sony/400/400',
    stock: 15,
    createdAt: Date.now(),
  },
  {
    id: '2',
    name: 'MacBook Air M2',
    price: 24500000,
    costPrice: 21000000,
    category: 'Laptop',
    condition: 'Hàng chính hãng 100%',
    description: 'Laptop mỏng nhẹ, hiệu năng mạnh mẽ với chip Apple M2, thời lượng pin cả ngày.',
    specs: "CPU: Apple M2 8-core\nRAM: 8GB Unified Memory\nSSD: 256GB\nMàn hình: 13.6 inch Liquid Retina\nTrọng lượng: 1.24 kg",
    warrantyPeriod: "12 tháng chính hãng",
    image: 'https://picsum.photos/seed/macbook/400/400',
    stock: 5,
    createdAt: Date.now(),
  },
  {
    id: '3',
    name: 'Giày Nike Air Jordan',
    price: 3500000,
    costPrice: 2200000,
    category: 'Thời trang',
    condition: 'Hàng cũ',
    description: 'Thiết kế cổ điển, phong cách thể thao năng động, thoải mái cho mọi hoạt động.',
    specs: "Chất liệu: Da cao cấp\nĐế giày: Cao su chống trượt\nKiểu dáng: Cổ cao (High-top)\nMàu sắc: Đỏ/Đen/Trắng",
    warrantyPeriod: "1 tháng",
    image: 'https://picsum.photos/seed/jordan/400/400',
    stock: 20,
    createdAt: Date.now(),
  },
  {
    id: '4',
    name: 'Đồng hồ cơ Seiko',
    price: 5200000,
    costPrice: 3800000,
    category: 'Phụ kiện',
    condition: 'Hàng chính hãng 100%',
    description: 'Sự tinh tế trong từng chuyển động, mặt kính sapphire chống xước.',
    specs: "Máy: Automatic 4R36\nKính: Sapphire Crystal\nĐường kính: 40mm\nChống nước: 10 ATM\nDây đeo: Thép không gỉ 316L",
    warrantyPeriod: "24 tháng",
    image: 'https://picsum.photos/seed/watch/400/400',
    stock: 8,
    createdAt: Date.now(),
  },
  // --- Linh kiện PC ---
  {
    id: '5',
    name: 'CPU Intel Core i9-14900K',
    price: 14990000,
    costPrice: 12500000,
    category: 'Linh kiện PC',
    condition: 'Hàng chính hãng 100%',
    description: 'Bộ vi xử lý Intel thế hệ 14 mạnh mẽ nhất, xung nhịp lên tới 6.0GHz, cân mọi tác vụ nặng.',
    specs: "Socket: LGA1700\nSố nhân: 24 (8 P-cores, 16 E-cores)\nSố luồng: 32\nXung nhịp tối đa: 6.0 GHz\nCache: 36MB Intel Smart Cache",
    warrantyPeriod: "36 tháng",
    image: 'https://picsum.photos/seed/cpu/400/400',
    stock: 10,
    createdAt: Date.now(),
  },
  {
    id: '6',
    name: 'VGA ASUS ROG Strix GeForce RTX 4090',
    price: 59990000,
    costPrice: 52000000,
    category: 'Linh kiện PC',
    condition: 'Hàng cũ',
    description: 'Card đồ họa khủng long bạo chúa, chiến game 4K Ultra Settings mượt mà.',
    specs: "VRAM: 24GB GDDR6X\nBus giao tiếp: 384-bit\nCổng kết nối: 2x HDMI 2.1a, 3x DisplayPort 1.4a\nNguồn đề xuất: 1000W\nKích thước: 3.5 slot",
    warrantyPeriod: "36 tháng",
    image: 'https://picsum.photos/seed/gpu/400/400',
    stock: 3,
    createdAt: Date.now(),
  },
  {
    id: '7',
    name: 'RAM Corsair Dominator Platinum RGB 32GB',
    price: 4500000,
    costPrice: 3500000,
    category: 'Linh kiện PC',
    condition: 'Hàng chính hãng 100%',
    description: 'Kit RAM DDR5 cao cấp với hệ thống LED RGB tuyệt đẹp và hiệu năng ổn định.',
    specs: "Dung lượng: 32GB (2x16GB)\nChuẩn: DDR5\nBus: 5600MHz\nLED: RGB Capellix\nTản nhiệt: Nhôm Anodized",
    warrantyPeriod: "36 tháng",
    image: 'https://picsum.photos/seed/ram/400/400',
    stock: 50,
    createdAt: Date.now(),
  },
  {
    id: '8',
    name: 'Mainboard ASUS ROG MAXIMUS Z790 HERO',
    price: 16500000,
    costPrice: 14000000,
    category: 'Linh kiện PC',
    condition: 'Hàng cũ',
    description: 'Bo mạch chủ cao cấp hỗ trợ ép xung cực tốt, đầy đủ cổng kết nối hiện đại nhất.',
    specs: "Chipset: Z790\nSocket: LGA1700\nHỗ trợ RAM: 4 khe DDR5 (Max 192GB)\nKhe mở rộng: 2x PCIe 5.0 x16\nKết nối mạng: Wi-Fi 6E, 2.5Gb Ethernet",
    warrantyPeriod: "36 tháng",
    image: 'https://picsum.photos/seed/mainboard/400/400',
    stock: 12,
    createdAt: Date.now(),
  },
  {
    id: '9',
    name: 'SSD Samsung 990 PRO 1TB M.2 NVMe',
    price: 2850000,
    costPrice: 2200000,
    category: 'Linh kiện PC',
    condition: 'Hàng chính hãng 100%',
    description: 'Ổ cứng SSD tốc độ đọc ghi siêu nhanh, khởi động Windows chỉ trong vài giây.',
    specs: "Dung lượng: 1TB\nChuẩn kết nối: PCIe Gen 4.0 x4, NVMe 2.0\nTốc độ đọc: 7450 MB/s\nTốc độ ghi: 6900 MB/s\nMTBF: 1.5 triệu giờ",
    warrantyPeriod: "60 tháng",
    image: 'https://picsum.photos/seed/ssd/400/400',
    stock: 30,
    createdAt: Date.now(),
  },
  {
    id: '10',
    name: 'Nguồn Corsair RM1000x Shift 1000W',
    price: 4890000,
    costPrice: 3900000,
    category: 'Linh kiện PC',
    condition: 'Hàng chính hãng 100%',
    description: 'Nguồn máy tính chuẩn Gold, fully modular, đảm bảo năng lượng ổn định cho dàn máy khủng.',
    specs: "Công suất: 1000W\nChuẩn: 80 Plus Gold\nQuạt làm mát: 140mm FDB Fan\nKiểu cáp: Full Modular (Cáp dẹt)\nBảo hành: 10 năm",
    warrantyPeriod: "120 tháng",
    image: 'https://picsum.photos/seed/psu/400/400',
    stock: 0,
    createdAt: Date.now(),
  }
];
